;;; custom.el --- Default Cat Emacs custom settings -*- lexical-binding: t; -*-

;;; Commentary:

;; This file is the fallback Custom file for Cat Emacs.  User customizations
;; should live in ~/.config/cat-emacs/custom.el.

;;; Code:

(custom-set-variables
 '(use-short-answers t)
 '(package-native-compile t)
 '(system-packages-use-sudo nil)
 '(package-selected-packages
   '(ace-pinyin
     ace-window
     activities
     agent-shell
     aider
     aidermacs
     android-mode
     anki-vocabulary
     ansible
     ansible-doc
     apheleia
     applescript-mode
     auctex
     avy
     avy-embark-collect
     bbdb
     beacon
     beancount
     benchmark-init
     bibtex-completion
     bing-dict
     breadcrumb
     bufler
     burly
     caddyfile-mode
     cape
     cdlatex
     chatgpt-shell
     chezmoi
     citar
     citar-embark
     citar-org-roam
     cmake-font-lock
     cmake-mode
     code-review
     codeium
     compile-multi
     compile-multi-embark
     compile-multi-nerd-icons
     consult
     consult-compile-multi
     consult-gh
     consult-gh-embark
     consult-gh-forge
     corfu
     corfu-prescient
     csv-mode
     dart-mode
     dashboard
     deft
     delight
     devdocs
     diff-hl
     dired-rsync
     dired-rsync-transient
     dirvish
     docker
     docker-compose-mode
     dockerfile-mode
     doom-modeline
     doom-themes
     dumb-jump
     easy-hugo
     eglot
     eldoc-box
     eldoc-toml
     elfeed
     elfeed-org
     elfeed-protocol
     elisp-demos
     elogcat
     emacs-everywhere
     embark
     embark-consult
     ement
     emms
     eshell-vterm
     exec-path-from-shell
     flycheck
     flycheck-gradle
     flycheck-kotlin
     flycheck-plantuml
     flycheck-pos-tip
     flycheck-posframe
     flymake-ansible-lint
     flymake-gradle
     forge
     ghostel
     git-link
     git-timemachine
     glab
     go-mode
     go-template-helper-mode
     go-template-mode
     goggles
     gogs
     golden-ratio
     gptel
     gptel-forge-prs
     gptel-magit
     graphql-mode
     grip-mode
     groovy-mode
     gt
     helpful
     hugoista
     igist
     immersive-translate
     indent-bars
     jabber
     kaolin-themes
     kdl-mode
     kotlin-mode
     kotlin-ts-mode
     leetcode
     ligature
     logview
     lsp-dart
     lua-mode
     magit
     magit-section
     magit-todos
     major-mode-hydra
     makefile-executor
     marginalia
     markdown-mode
     meow
     meow-tree-sitter
     mermaid-mode
     minimap
     mistty
     mpv
     mu4e-column-faces
     mu4e-overview
     mustache
     nerd-icons
     nerd-icons-completion
     nerd-icons-corfu
     nerd-icons-dired
     no-littering
     nov
     ob-aider
     ob-applescript
     ob-async
     ob-go
     ob-kotlin
     ob-powershell
     ob-rust
     ob-swiftui
     ob-typescript
     org
     org-anki
     org-appear
     org-cliplink
     org-drill
     org-edna
     org-link-beautify
     org-modern
     org-modern-indent
     org-noter
     org-pdftools
     org-roam
     org-roam-bibtex
     org-roam-ui
     osm
     osx-dictionary
     ox-hugo
     pangu-spacing
     pass
     password-store
     password-store-menu
     pdf-tools
     pet
     pinyin-isearch
     pinyin-search
     plantuml-mode
     poetry
     poly-ansible
     polymode
     powershell
     promise
     protobuf-mode
     pulsar
     rainbow-csv
     rainbow-mode
     rg
     rime
     rust-mode
     shell-maker
     sideline
     sideline-blame
     sideline-eglot
     sideline-flycheck
     sideline-flymake
     smartparens
     solaire-mode
     swift-mode
     swift-ts-mode
     system-packages
     tabspaces
     telega
     templ-ts-mode
     templatel
     toc-mode
     transient
     transpose-frame
     treemacs
     treemacs-magit
     treemacs-nerd-icons
     treemacs-tab-bar
     treesit-auto
     treesit-fold
     treesit-langs
     ultra-scroll
     undo-fu-session
     uv-mode
     valign
     vbs-repl
     vbscript-mode
     vertico
     vertico-prescient
     visual-basic-mode
     vlf
     vterm
     vterm-toggle
     vundo
     which-key
     winum
     yaml-pro
     yasnippet)))

;;; custom.el ends here
