name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 29.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        path: ~/.emacs.d/

      - name: Setup Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Setup custom
        run: echo "(custom-set-variables '(use-short-answers t) '(package-native-compile t))" > ~/.emacs.d/custom.el

      - name: Run init
        run: yes | emacs --fg-daemon --debug-init --eval "(kill-emacs)"

  docker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cat-emacs
            ghcr.io/${{ github.repository }}

      - name: Emacs Build Cache for Docker
        uses: actions/cache@v4
        with:
          path: emacs-build-cache
          key: ${{ runner.os }}-emacs-build-cache-${{ hashFiles('config.el') }}

      - name: Inject emacs-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v2
        with:
          cache-source: emacs-build-cache

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
